### ISSUE TITLE
Failed to download ruby

### ISSUE THREAD

**Issue by vickydasta** [darkoperator/MSF-Installer#34]
when i run the script,after finished to download dependencies,and start to download the ruby,after a while it's stoped and show error bellow : 
Failed to download and install Ruby Gems for running Metasploit Framework

**Comment by clumsyninja83** [comment]
thanks for the great program.  The issue seems to be two separate things, easily fixed.

1. the script isn't installing the gems (at least for me in wheezy), fixed by going to /usr/share/metasploit-framework/ and running "bundle install".

2. the postgresql database isn't being made correctly, fixable by becoming postgres ("su postgres" as root) and then inputting "createuser msf -P -S -R -D" and filling in the info.  also double-check the info in /usr/share/metasploit-framework/config/database.yml.  I had to change values in there, but I was also screwing with it while trying to make this work.

If need be, I can recreate the entire thing and record it for you.  Again, thanks for your time and effort.
