### ISSUE TITLE
could you help me?

### ISSUE THREAD

**Issue by immac99w** [darkoperator/MSF-Installer#39]
Doing the install for metasploit on Yosemite10.10
i have some error.

[*] Decompressing package to /usr/local/share/armitage
./msf_install.sh: line 72: $LOGFILE: ambiguous redirect
./msf_install.sh: line 73: $LOGFILE: ambiguous redirect
[*] OS X Was unable to decompress the latest version of Armitage
./msf_install.sh: line 76: $LOGFILE: ambiguous redirect
[*] Installing additional Metasploit plugins
[*] Installing Pentest plugin
Warning: Failed to create the file 
Warning: /usr/local/share/metasploit-framework/plugins/pentest.rb: No such 
Warning: file or directory

curl: (23) Failed writing body (0 != 7339)
[*] Failed to install the pentest plugin.
[*] Installing DNSRecon Import plugin
Warning: Failed to create the file 
Warning: /usr/local/share/metasploit-framework/plugins/dnsr_import.rb: No such 
Warning: file or directory

curl: (23) Failed writing body (0 != 6880)
[*] Failed to install the dnsr_import plugin.
[*] #################################################################
[*] ### YOU NEED TO RELOAD YOUR PROFILE BEFORE USE OF METASPLOIT!   ###
[*] ### RUN source ~/.bash_profile                                  ###
[*] ###                                                             ###
[*] ### INSTALLATION WAS USING RVM, SET 1.9.3 AS DEFAULT            ###
[*] ### RUN rvm use ruby-1.9.3-p550 --default                       ###
[*] ###                                                             ###
[*] ###################################################################

**Comment by darkoperator** [comment]
Those are just extra stuff I added. Find the error to be a weird one will have to look in to it. Is msfconsole working?

**Comment by immac99w** [comment]
No T-T... It's NOT working ...

**Comment by darkoperator** [comment]
Since the info you are giving me is kind of limited :) what steps have you taken to fix it? what error is giving you msfconsole when you run it directly from the folder it self where it was cloned, you cannot run is from the symlink there is a bug that prevents it from running it from. did you installed with RVM? if so did you checked you where running the proper version of ruby that it installed by listing and then checking that it is the default? did you made sure environment variables where loaded by reloading the profile?
